sudo: required

services:
  - docker

before-install:
  - docker build -t vmh/docker-react -f Dockerfile.dev .

script:
  - docker run vmh/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region:  "us-west-2"
  app: "docker-react"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-west-2-dgdgdgdf"
  bucket_path: "docker-react"
  on: 
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"